import { Platform, StyleSheet } from 'react-native';

export default StyleSheet.create({
  menu: {
    backgroundColor: '#F1F2F4',
  },
  divTitle:{
    backgroundColor: "#F1F2F4",
    padding: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderColor: '#092955',
    marginBottom: 10,
  },
  divTitleMain:{
    backgroundColor: "#F1F2F4",
    padding: '5%',
    paddingBottom: '5%',
    marginLeft: '1%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleText:{
    fontSize: 18,
    marginLeft: 20,
    marginRight: 80,
    color: '#092955',
  },
  titleTextMain:{
    fontSize: 24,
    marginRight: '55%',
    color: '#092955',
    fontWeight: 'bold',
  },
  input: {
    width: '100%',
    height: 40,
    backgroundColor: '#fff',
    borderColor: 'transparent',
    borderWidth: 3,
    borderRadius: 8,
    marginBottom: 5,
    paddingLeft: 15,
    fontWeight: 'bold',
    fontSize: Platform.OS === 'ios' ? 14 : 10,
  },
  label: {
    margin: 10,
  },
  content: {
    margin: 30
  },
  button: {
    width: 85,
    height: 40,
    borderRadius: 50,
    backgroundColor: '#092955',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 200,
    marginLeft: 125,
  }, 
  buttonText: {
    color: '#FFFFFF'
  },
  dateInput: {
    borderColor: 'transparent',
    backgroundColor: '#fff',
    borderWidth: 3,
    borderRadius: 8, 
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    display: 'flex',
    flexDirection: 'row',
  },
  dateText: {
    textAlign: 'center',
    fontWeight: 'bold',
    paddingLeft: 100,
    fontSize: Platform.OS === 'ios' ? 14 : 10,
  },
  listItem: {
    backgroundColor: '#FFFFFF',
    padding: 15,
    marginTop: 10,
    borderRadius: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 3 }, 
    shadowOpacity: 0.3, 
    shadowRadius: 4, 
    elevation: 5,
  },
  listText: {
    fontSize: Platform.OS === 'ios' ? 14 : 10,
    color: '#000'
  }, contentList: {
    margin: 5
  },
  listButtonEdit: {
    backgroundColor: '#092955',
    padding: 3,
    width: 80,
    borderRadius: 8,
    marginLeft: 5,
    marginRight: 5,
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly'
  },
  listButtonSearch: {
    backgroundColor: '#092955',
    padding: 4,
    width: 55,
    borderRadius: 8,
    marginTop: 3,
    marginBottom: 10,
    marginLeft: 5,
    textAlign: 'center'
  },
  listButtonDelete: {
    borderColor: '#ccc',
    padding: '1%',
    width: 30,
    borderRadius: 8,
    marginLeft: 5,
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly'
  },
  listButtons: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  search: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center'
  }, 
  scheduleButton: {
    backgroundColor: '#092955',
    width: 70,
    height: 30,
    borderRadius: 8,
    marginLeft: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingBottom: 2,
    paddingRight: 2,
    marginBottom: 20,
    marginTop: 10,
  },
  scheduleText: {
    color: '#FFFFFF',
  },
  selectListBox: {
    width: '90%',
    maxWidth: 352, 
    height: 45,
    borderRadius: 10,
    borderWidth: 3,
    borderColor: 'transparent',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    marginTop: 10,
    paddingTop: 9,
    fontSize: Platform.OS === 'ios' ? 14 : 10,
  },
  selectListInput: {
    fontSize: Platform.OS === 'ios' ? 14 : 10,
    paddingTop: '1.5%',
    color: '#000',
  },
  selectListDropdown: {
    borderRadius: 10,
    borderWidth: 3,
    borderColor: 'transparent',
    backgroundColor: '#FFFFFF',
    marginHorizontal: 20,
    fontSize: Platform.OS === 'ios' ? 14 : 10,
  },
})
